// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/calculator_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/calculator_service.go -destination=internal/mocks/service/calculator_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCalculatorService is a mock of CalculatorService interface.
type MockCalculatorService struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorServiceMockRecorder
	isgomock struct{}
}

// MockCalculatorServiceMockRecorder is the mock recorder for MockCalculatorService.
type MockCalculatorServiceMockRecorder struct {
	mock *MockCalculatorService
}

// NewMockCalculatorService creates a new mock instance.
func NewMockCalculatorService(ctrl *gomock.Controller) *MockCalculatorService {
	mock := &MockCalculatorService{ctrl: ctrl}
	mock.recorder = &MockCalculatorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculatorService) EXPECT() *MockCalculatorServiceMockRecorder {
	return m.recorder
}

// Division mocks base method.
func (m *MockCalculatorService) Division(first, second float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Division", first, second)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Division indicates an expected call of Division.
func (mr *MockCalculatorServiceMockRecorder) Division(first, second any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Division", reflect.TypeOf((*MockCalculatorService)(nil).Division), first, second)
}

// Exponentiation mocks base method.
func (m *MockCalculatorService) Exponentiation(base, exponent float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exponentiation", base, exponent)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exponentiation indicates an expected call of Exponentiation.
func (mr *MockCalculatorServiceMockRecorder) Exponentiation(base, exponent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exponentiation", reflect.TypeOf((*MockCalculatorService)(nil).Exponentiation), base, exponent)
}

// Multiply mocks base method.
func (m *MockCalculatorService) Multiply(first, second float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Multiply", first, second)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Multiply indicates an expected call of Multiply.
func (mr *MockCalculatorServiceMockRecorder) Multiply(first, second any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Multiply", reflect.TypeOf((*MockCalculatorService)(nil).Multiply), first, second)
}

// Percentage mocks base method.
func (m *MockCalculatorService) Percentage(value float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Percentage", value)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Percentage indicates an expected call of Percentage.
func (mr *MockCalculatorServiceMockRecorder) Percentage(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Percentage", reflect.TypeOf((*MockCalculatorService)(nil).Percentage), value)
}

// SquareRoot mocks base method.
func (m *MockCalculatorService) SquareRoot(value float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SquareRoot", value)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SquareRoot indicates an expected call of SquareRoot.
func (mr *MockCalculatorServiceMockRecorder) SquareRoot(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SquareRoot", reflect.TypeOf((*MockCalculatorService)(nil).SquareRoot), value)
}

// Subtract mocks base method.
func (m *MockCalculatorService) Subtract(first, second float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subtract", first, second)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subtract indicates an expected call of Subtract.
func (mr *MockCalculatorServiceMockRecorder) Subtract(first, second any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subtract", reflect.TypeOf((*MockCalculatorService)(nil).Subtract), first, second)
}

// Sum mocks base method.
func (m *MockCalculatorService) Sum(first, second float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", first, second)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sum indicates an expected call of Sum.
func (mr *MockCalculatorServiceMockRecorder) Sum(first, second any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockCalculatorService)(nil).Sum), first, second)
}
