// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculator"
                ],
                "summary": "Perform arithmetic operation",
                "parameters": [
                    {
                        "type": "number",
                        "description": "First operand",
                        "name": "first",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Second operand",
                        "name": "second",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "sum",
                            "subtract",
                            "multiply",
                            "division"
                        ],
                        "type": "string",
                        "description": "Operation",
                        "name": "op",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_handler.CalculateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/sezzle-calculator-api_internal_infrastructure_error.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/sezzle-calculator-api_internal_infrastructure_error.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_handler.CalculateResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "number"
                }
            }
        },
        "sezzle-calculator-api_internal_infrastructure_error.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Sezzle Calculator API",
	Description:      "A single-endpoint arithmetic API.\nEvery error response shares one shape. requestId correlates with the server logs, and error carries the raw internal error but is only populated under the dev profile.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
